---
- hosts: aws_ec2
  become: true
  remote_user: ec2-user
  gather_facts: false
  vars:
    ansible_ssh_private_key_file: "/home/ec2-user/new-key.pem"  
    ansible_ssh_user: "ec2-user"
  tasks:
# tasks file for webproject

  - name: installation of git
    yum:
      name: git
      state: present

  - name: cloning code from git hub 
    git:
      repo: https://github.com/wahtej/php.git
      dest: /php 


  - name: install dependencies
    command: yum install -y httpd wget php-fpm php-mysqli php-json php php-devel
    become: true

  - name: Make sure apache is running
    systemd:
      state: started
      name: httpd

  - name: moving code to default directory
    become: true
    command: mv /php /var/www/html

